In [2]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [34]:
gc = pd.read_csv('german_credit.csv')
                #names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])
gc.head()

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,...,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,...,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,...,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,...,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,...,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

In [0]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable

(1000, 21)
Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,...,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,...,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,...,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,...,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,...,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [10]:
# splitting data into training and test set for independent attributes
from sklearn.model_selection import train_test_split

X =  gc.drop("default", axis=1)
y =  gc.pop("default")
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.5,random_state=0)

In [0]:
# Lets build a Ensemble model but need to modify the dataset first

### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [30]:
xtrain_D=pd.get_dummies(xtrain)
xtrain_D.head()

,duration_in_month,credit_amount,installment_as_income_perc,present_res_since,age,credits_this_bank,people_under_maintenance,account_check_status_0 <= ... < 200 DM,account_check_status_< 0 DM,account_check_status_>= 200 DM / salary assignments for at least 1 year,...,housing_own,housing_rent,job_management/ self-employed/ highly qualified employee/ officer,job_skilled employee / official,job_unemployed/ unskilled - non-resident,job_unskilled - resident,telephone_none,"telephone_yes, registered under the customers name",foreign_worker_no,foreign_worker_yes
631,18,1553,4,3,44,1,1,0,1,0,...,1,0,0,1,0,0,1,0,0,1
185,15,1360,4,2,31,2,1,0,0,0,...,1,0,0,1,0,0,1,0,0,1
732,8,760,4,2,44,1,1,1,0,0,...,1,0,0,0,0,1,1,0,0,1
404,18,2899,4,4,43,1,2,1,0,0,...,1,0,0,1,0,0,1,0,0,1
194,45,3031,4,4,21,1,1,1,0,0,...,0,1,0,1,0,0,1,0,0,1

In [16]:
# Print Shape of model data
xtrain_D.shape

(500, 61)

### Check for highly correlated variables but don't required any treatment for this use case

In [37]:
gc_D=pd.get_dummies(gc)
gc_D.head()

,default,duration_in_month,credit_amount,installment_as_income_perc,present_res_since,age,credits_this_bank,people_under_maintenance,account_check_status_0 <= ... < 200 DM,account_check_status_< 0 DM,...,housing_own,housing_rent,job_management/ self-employed/ highly qualified employee/ officer,job_skilled employee / official,job_unemployed/ unskilled - non-resident,job_unskilled - resident,telephone_none,"telephone_yes, registered under the customers name",foreign_worker_no,foreign_worker_yes
0,0,6,1169,4,4,67,2,1,0,1,...,1,0,0,1,0,0,0,1,0,1
1,1,48,5951,2,2,22,1,1,1,0,...,1,0,0,1,0,0,1,0,0,1
2,0,12,2096,2,3,49,1,2,0,0,...,1,0,0,0,0,1,1,0,0,1
3,0,42,7882,2,4,45,1,2,0,1,...,0,0,0,1,0,0,1,0,0,1
4,1,24,4870,3,4,53,2,2,0,1,...,0,0,0,1,0,0,1,0,0,1

In [38]:
gc.corr()

,default,duration_in_month,credit_amount,installment_as_income_perc,present_res_since,age,credits_this_bank,people_under_maintenance
default,1.000000,0.214927,0.154739,0.072404,0.002967,-0.091127,-0.045732,-0.003015
duration_in_month,0.214927,1.000000,0.624984,0.074749,0.034067,-0.036136,-0.011284,-0.023834
credit_amount,0.154739,0.624984,1.000000,-0.271316,0.028926,0.032716,0.020795,0.017142
installment_as_income_perc,0.072404,0.074749,-0.271316,1.000000,0.049302,0.058266,0.021669,-0.071207
present_res_since,0.002967,0.034067,0.028926,0.049302,1.000000,0.266419,0.089625,0.042643
age,-0.091127,-0.036136,0.032716,0.058266,0.266419,1.000000,0.149254,0.118201
credits_this_bank,-0.045732,-0.011284,0.020795,0.021669,0.089625,0.149254,1.000000,0.109667
people_under_maintenance,-0.003015,-0.023834,0.017142,-0.071207,0.042643,0.118201,0.109667,1.000000

### Drop the original variables which are converted to dummy

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [39]:
#xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.5,random_state=0)
# splitting data into training and test set for independent attributes
from sklearn.model_selection import train_test_split

X =  gc_D.drop("default", axis=1)
y =  gc_D.pop("default")
train_set, test_set, train_labels, test_labels = train_test_split(X, y, test_size=0.30, random_state=2)

### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [40]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection
from sklearn import metrics
#from sklearn.decomposition import PCA
from scipy.stats import zscore
import matplotlib.pyplot as plt 

Rf_model = RandomForestClassifier(n_estimators=500,criterion='entropy',max_depth=4,random_state=9999 )

In [41]:
Rf_model.fit(train_set, train_labels)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=4, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=9999, verbose=0,
            warm_start=False)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [44]:
y_predict_Rf=Rf_model.predict(test_set)

In [45]:
Rf_acc=metrics.accuracy_score(test_labels,y_predict_Rf)
print(Rf_acc)

0.6866666666666666

In [ ]:
cm=metrics.confusion_matrix(test_set,y_predict_Rf)
print(cm)

### Q6 Show the list of the features importance( 1 Marks)

In [51]:
# importance of features in the tree building ( The importance of a feature is computed as the 
#(normalized) total reduction of the criterion brought by that feature. It is also known as the Gini importance )

print (pd.Series(Rf_model.feature_importances_,index = list(X)).sort_values(ascending=False))

account_check_status_no checking account                                      0.136465
credit_amount                                                                 0.082823
account_check_status_< 0 DM                                                   0.081168
duration_in_month                                                             0.065261
age                                                                           0.051700
savings_... < 100 DM                                                          0.042715
credit_history_critical account/ other credits existing (not at this bank)    0.035801
savings_unknown/ no savings account                                           0.032963
property_real estate                                                          0.030989
property_unknown / no property                                                0.024993
housing_own                                                                   0.023869
account_check_status_0 <= ... < 200 DM                                        0.022980
purpose_car (used)                                                            0.019982
installment_as_income_perc                                                    0.017997
purpose_domestic appliances                                                   0.016286
account_check_status_>= 200 DM / salary assignments for at least 1 year       0.015288
present_res_since                                                             0.014247
other_installment_plans_bank                                                  0.014220
personal_status_sex_male : single                                             0.013902
credit_history_no credits taken/ all credits paid back duly                   0.013564
other_installment_plans_none                                                  0.013531
present_emp_since_4 <= ... < 7 years                                          0.012613
purpose_car (new)                                                             0.012580
present_emp_since_... < 1 year                                                0.012449
housing_rent                                                                  0.011346
personal_status_sex_female : divorced/separated/married                       0.010770
credits_this_bank                                                             0.009646
credit_history_all credits at this bank paid back duly                        0.008634
housing_for free                                                              0.007337
present_emp_since_.. >= 7 years                                               0.007267
                                                                                ...
job_management/ self-employed/ highly qualified employee/ officer             0.007048
credit_history_delay in paying off in the past                                0.006777
purpose_business                                                              0.006605
job_skilled employee / official                                               0.006516
purpose_(vacation - does not exist?)                                          0.006421
other_debtors_guarantor                                                       0.006371
credit_history_existing credits paid back duly till now                       0.006289
savings_.. >= 1000 DM                                                         0.006016
telephone_none                                                                0.006015
people_under_maintenance                                                      0.005438
savings_500 <= ... < 1000 DM                                                  0.005115
property_if not A121/A122 : car or other, not in attribute 6                  0.005032
savings_100 <= ... < 500 DM                                                   0.004569
present_emp_since_1 <= ... < 4 years                                          0.004435
other_debtors_co-applicant                                                    0.004368
foreign_worker_yes                                                            0.004170
purpose_radio/television                                                      0.004079
property_if not A121 : building society savings agreement/ life insurance     0.003999
job_unskilled - resident                                                      0.003970
other_debtors_none                                                            0.003825
present_emp_since_unemployed                                                  0.003333
purpose_education                                                             0.003327
personal_status_sex_male : divorced/separated                                 0.003298
personal_status_sex_male : married/widowed                                    0.002885
foreign_worker_no                                                             0.002665
purpose_repairs                                                               0.001784
other_installment_plans_stores                                                0.001669
purpose_furniture/equipment                                                   0.001636
job_unemployed/ unskilled - non-resident                                      0.001261
purpose_retraining                                                            0.000448
Length: 61, dtype: float64

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [52]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [0]:
# Use below values
num_folds = 10
seed = 77

In [0]:
#Validate the Random Forest model build above using k fold

In [54]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,shuffle=True,random_state=2)
for model, name in zip([Rf_model], ['RF']):
    k=0
    recall=np.zeros((2,5))
    prec=np.zeros((2,5))
    fscore=np.zeros((2,5))
    for train,test in kf.split(X,y):
        Xtrain,Xtest=X[train,:],X[test,:]
        Ytrain,Ytest=Y[train],Y[test]
        model.fit(Xtrain,Ytrain)
        Y_predict=model.predict(Xtest)
        cm=metrics.confusion_matrix(Ytest,Y_predict)
        for i in np.arange(0,2):
            recall[i,k]=cm[i,i]/cm[i,:].sum()
        for i in np.arange(0,2):
            prec[i,k]=cm[i,i]/cm[:,i].sum()
        k=k+1
    for row in np.arange(0,2):
        for col in np.arange(0,5):
            fscore[row,col]=2*(recall[row,col]*prec[row,col])/(recall[row,col]+prec[row,col])
    print("f1_weighted for Healthy: %0.02f (+/- %0.5f) [%s]" % (np.mean(fscore[0,:]), np.var(fscore[0,:],ddof=1), name ))   
    print("f1_weighted for Diabetic: %0.02f (+/- %0.5f) [%s]" % (np.mean(fscore[1,:]), np.var(fscore[1,:],ddof=1), name ))

TypeError: unhashable type: 'numpy.ndarray'

In [0]:
#Calculate Mean score

In [0]:
# Calculate score standard deviation using std()

# Q8 Print the confusion matrix( 1 Marks)

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [0]:
#Hint: Use roc_curve

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [0]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [0]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(X_train, y_train)
    rfm.fit(X_, y_)
    y_pred = rfm.predict(X_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

In [0]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  0.6893333333333334
Standard deviation:  0.014966629547095768